; Stationery · Calendar — its words in Simplified Chinese. Original work, MIT licensed.
; The same keys as Strings-English.inc. Chinese needs its own format for another year: Chinese %b is "1月".

[Variables]
CalendarMonthFormat0=%B
CalendarMonthFormat1=%Y年%#m月
CalendarMonthYearFormat=%Y年%#m月
CalendarToday=今天
CalendarGoToToday=回到今天
CalendarWeekText=第 %1 周
CalendarSentence=第 [MeasureWeekNow] 周，今年第 [MeasureDayOfYear] 天（共 [MeasureYearDays] 天）。[#Moon[&MeasureMoonEighth:0]]。
CalendarMenuOpen=打开日历
CalendarMenuWeekNumbers0=周数：关
CalendarMenuWeekNumbers1=周数：开
CalendarMenuMoon0=月相：关
CalendarMenuMoon1=月相：开
