import Foundation

/// Chinese for the words `EditorSchema` writes in English: the labels of options the Studio's catalog does not list
/// (Every Setting and a data item's page show them) and the titles of their choices. Keyed by the English words, so a
/// label shared by several options is translated once.
public enum StudioSchemaChinese {
    /// An option's label in Chinese (nil: not in the table).
    public static func label(_ english: String) -> String? { labels[english] }

    /// A choice's title in Chinese (nil: not in the table; numbers and names are shown as they are).
    public static func choice(_ english: String) -> String? {
        if let zh = choices[english] { return zh }
        // "Core 7" → "核心 7".
        if english.hasPrefix("Core "), Int(english.dropFirst(5)) != nil { return "核心 " + english.dropFirst(5) }
        return nil
    }

    /// Every label and choice title Every Setting can show for a part or a data item (the self-tests check each has
    /// Chinese).
    public static func reachable() -> (labels: Set<String>, choices: Set<String>) {
        var labels: Set<String> = [], choices: Set<String> = []
        var items: [StudioCatalog.Item] = []
        for type in EditorSchema.meterTypes { items += StudioCatalog.items(forMeterType: type) }
        for type in EditorSchema.measureTypes {
            items += StudioCatalog.items(forMeasureType: type.isPlugin ? "Plugin" : type.name,
                                         plugin: type.isPlugin ? type.name : nil)
        }
        for item in items where StudioCatalog.field(item.property.key) == nil {
            labels.insert(item.property.label)
            if case .choice(let list, _) = item.property.kind {
                for c in list where needsWords(c.title) { choices.insert(c.title) }
            }
        }
        for c in EditorSchema.alignments where needsWords(c.title) { choices.insert(c.title) }
        return (labels, choices)
    }

    /// A title with words to translate (not a number, a unit or a name written as it is).
    static func needsWords(_ title: String) -> Bool {
        guard title.contains(where: \.isLetter), !title.allSatisfy({ $0.isUppercase || $0.isNumber || !$0.isLetter })
        else { return false }
        // A name written as the engine reads it ("ButtonFace", "GetCurrentTrackAlbum", "Dark1", "hPa"): shown as it is.
        if !title.contains(" "), title.dropFirst().contains(where: { $0.isUppercase || $0.isNumber }) { return false }
        return true
    }

    /// What breaks Apple's Chinese style in `text`: Chinese right next to a Latin letter or a digit (a space goes
    /// between), half-width punctuation next to Chinese, straight quotes, three dots for an ellipsis. Placeholders
    /// (`%@`, `%d`, `%1$@`) are left alone: what fills them decides.
    public static func styleProblems(_ text: String) -> [String] {
        var problems: [String] = []
        let chars = Array(text.replacingOccurrences(of: #"%(\d\$)?[@dlu]+"#, with: "\u{E000}",
                                                    options: .regularExpression))
        func han(_ c: Character) -> Bool {
            c.unicodeScalars.contains { (0x4E00...0x9FFF).contains($0.value) || (0x3400...0x4DBF).contains($0.value) }
        }
        func latin(_ c: Character) -> Bool { c.isASCII && (c.isLetter || c.isNumber) }
        let halfWidth: Set<Character> = [",", ".", ":", ";", "?", "!", "(", ")"]
        for (a, b) in zip(chars, chars.dropFirst()) {
            if (han(a) && latin(b)) || (latin(a) && han(b)) { problems.append("no space in “\(a)\(b)”") }
            if (han(a) && halfWidth.contains(b)) || (halfWidth.contains(a) && han(b)) {
                problems.append("half-width punctuation in “\(a)\(b)”")
            }
        }
        if text.contains("\"") || text.contains("'") { problems.append("straight quotes") }
        if text.contains("...") { problems.append("three dots") }
        return problems
    }

    static let labels: [String: String] = [
        "Above": "高于",
        "Adapter": "网络适配器",
        "Address": "地址",
        "After each ping": "每次 ping 之后",
        "Alignment": "对齐",
        "Analysis size": "分析大小",
        "App": "App",
        "App number": "App 序号",
        "Artwork when missing": "没有插图时",
        "Ascending": "升序",
        "Available": "可用",
        "Back button": "后退键",
        "Back button double-click": "连按后退键",
        "Back button press": "按下后退键",
        "Band": "频段",
        "Band count": "频段数",
        "Bars": "柱子",
        "Below": "低于",
        "Bits": "位",
        "Border": "边框",
        "Border color": "边框颜色",
        "Button": "按钮",
        "Camera orientation": "镜头方向",
        "Center X": "中心 X",
        "Center Y": "中心 Y",
        "Change": "变化量",
        "Channel": "声道",
        "Channels": "声道",
        "Close on focus loss": "失去焦点时关闭",
        "Color": "颜色",
        "Color of": "颜色取自",
        "Combine": "合并",
        "Command": "命令",
        "Core": "核心",
        "Corners": "圆角",
        "Counter": "计数器",
        "Counter group": "计数器组",
        "Counts": "统计",
        "Cover when missing": "没有封面时",
        "Crop": "裁剪",
        "Curve height": "曲线高度",
        "Curve width": "曲线宽度",
        "Custom transform": "自定变换",
        "Dark": "深色",
        "Daylight saving": "夏令时",
        "Days as hours": "天数折成小时",
        "Days from today": "从今天起的天数",
        "Debug": "调试",
        "Debug file": "调试文件",
        "Decode \\u escapes": "解码 \\u 转义",
        "Decode entities": "解码字符实体",
        "Device": "设备",
        "Digit spacing": "数字间距",
        "Digits": "数字位数",
        "Direction": "方向",
        "Disk": "磁盘",
        "Disk type": "磁盘类型",
        "Display or adapter": "显示器或显卡",
        "Download": "下载",
        "Edge light": "边缘高光",
        "Edge shadow": "边缘阴影",
        "Edges that don't stretch": "不拉伸的边",
        "Effect": "效果",
        "Encoding": "编码",
        "End at": "结束于",
        "Equal to": "等于",
        "Extensions": "扩展名",
        "Fallback background": "备用背景",
        "Falls": "下降",
        "File or folder": "文件或文件夹",
        "File types": "文件类型",
        "Files": "文件",
        "Filter": "过滤",
        "Fit": "适应",
        "Fixed ends": "固定两端",
        "Fixed time": "固定时间",
        "Fixed time format": "固定时间的格式",
        "Fixed time language": "固定时间的语言",
        "Flags": "标志",
        "Flip": "翻转",
        "Flip mask": "翻转遮罩",
        "Flip the value": "反转数值",
        "Folder": "文件夹",
        "Folders": "文件夹",
        "Formula": "公式",
        "Forward button": "前进键",
        "Forward button double-click": "连按前进键",
        "Forward button press": "按下前进键",
        "Frames": "帧数",
        "Free": "可用",
        "Glass corner radius": "玻璃圆角",
        "Grayscale": "灰度",
        "Grid color": "网格颜色",
        "Group names": "分组名称",
        "Grow up to height": "最高长到",
        "Grow up to width": "最宽长到",
        "Held down for": "按住时长",
        "Hex": "十六进制",
        "Hidden files": "隐藏文件",
        "Hide tooltip": "隐藏提示",
        "Highest frequency": "最高频率",
        "Highest value": "最大值",
        "Hours from now": "从现在起的小时数",
        "Hours in the curve": "曲线的小时数",
        "Icon style": "图标样式",
        "Image": "图片",
        "Instance": "实例",
        "Item": "项目",
        "Items per page": "每页项目数",
        "Key": "键",
        "Language": "语言",
        "Leave out": "排除",
        "Leave out apps": "排除的 App",
        "Length offset": "长度偏移",
        "Level falls": "电平下降",
        "Level gain": "电平增益",
        "Level rises": "电平上升",
        "Line width": "线宽",
        "Lines": "行数",
        "List style": "列表样式",
        "Listen to": "收听",
        "Listens to": "收听",
        "Live values": "实时数值",
        "Log errors": "记录错误",
        "Lowest frequency": "最低频率",
        "Lowest value": "最小值",
        "Mask": "遮罩",
        "Mask folder": "遮罩文件夹",
        "Maximum length": "最大长度",
        "Middle double-click": "连按中键",
        "Middle press": "按下中键",
        "Move actions at most every": "移动动作最多每隔",
        "Name": "名称",
        "Network": "网络",
        "Networks in the list": "列表中的网络",
        "New random number": "新的随机数",
        "Number": "数字",
        "Number of digits": "位数",
        "Number shows": "数字显示",
        "Numbers": "数字",
        "Only apps": "只包括的 App",
        "Only names matching": "只包括名称符合",
        "Otherwise": "否则",
        "Output": "输出",
        "Output encoding": "输出编码",
        "Overlap": "重叠",
        "Overlap color": "重叠颜色",
        "Overlap picture": "重叠图片",
        "Parent": "上级",
        "Parent entry": "上级条目",
        "Password": "密码",
        "Pattern": "模式",
        "Patterns": "模式",
        "Paused": "暂停",
        "Peak falls": "峰值下降",
        "Peak rises": "峰值上升",
        "Percent": "百分比",
        "Picture": "图片",
        "Picture folder": "图片文件夹",
        "Piece": "片段",
        "Ping every": "ping 的间隔",
        "Place": "地点",
        "Player": "播放器",
        "Pointer shape": "指针形状",
        "Position from": "位置起点",
        "Press": "按下",
        "Pressure in": "气压单位",
        "Processor": "处理器",
        "Program": "程序",
        "Proxy": "代理",
        "Rain in": "降水单位",
        "Random from": "随机数下限",
        "Random to": "随机数上限",
        "Rank": "名次",
        "Rank by": "排名依据",
        "Reads": "读取",
        "Redraw": "重绘",
        "Reload every": "重新载入间隔",
        "Removable disks": "可移除磁盘",
        "Repeat": "重复",
        "Repeat every": "重复间隔",
        "Repeat matches": "重复匹配",
        "Replace text": "替换文字",
        "Reverse": "反向",
        "Right double-click": "连按右键",
        "Right press": "按下右键",
        "Rises": "上升",
        "Root": "根键",
        "Rotate mask": "旋转遮罩",
        "Rotation": "旋转",
        "Round to": "舍入到",
        "Same place as": "和它同一地点",
        "Sample": "样本",
        "Save as": "存储为",
        "Save output to": "输出存储到",
        "Script": "脚本",
        "Scroll left": "向左滚动",
        "Scroll right": "向右滚动",
        "Second color": "第二颜色",
        "Second picture": "第二张图片",
        "Seconds": "秒",
        "Sensitivity": "灵敏度",
        "Sensor": "传感器",
        "Separator": "分隔符",
        "Sequence 1": "序列 1",
        "Short times": "短时间格式",
        "Show": "显示",
        "Shows": "显示",
        "Slice": "切片",
        "Smooth": "平滑",
        "Smoothing": "平滑度",
        "Sort by": "排序方式",
        "Spaces": "空格",
        "Start and stop": "开始和停止",
        "Start at": "开始于",
        "Start offset": "起点偏移",
        "Step": "步长",
        "Stop after": "停止于",
        "Sub-piece": "子片段",
        "Subfolders": "子文件夹",
        "Symbol size": "符号大小",
        "System files": "系统文件",
        "System sounds": "系统声音",
        "Temperature in": "温度单位",
        "Text": "文字",
        "Text in the box": "框里的文字",
        "Text matches": "文字符合",
        "Text on error": "出错时的文字",
        "Text shows": "文字显示",
        "Text when the sun doesn't rise or set": "太阳不升不落时的文字",
        "Text when there is no data": "没有数据时的文字",
        "Text without a place": "没有地点时的文字",
        "Then": "那么",
        "Tile": "平铺",
        "Time zone": "时区",
        "Timeout": "超时",
        "Times": "次数",
        "Tint": "着色",
        "Total": "总量",
        "Transition frames": "过渡帧数",
        "Turned off": "已关闭",
        "Unique": "不重复",
        "Unit": "单位",
        "Units": "单位",
        "Update every": "更新间隔",
        "Used": "已用",
        "User agent": "用户代理",
        "Uses looks": "使用外观",
        "Value": "数值",
        "Value moves inner end": "数值移动内端",
        "Value moves outer end": "数值移动外端",
        "Value turns": "数值转动",
        "Value without reply": "没有回应时的数值",
        "Warnings": "警告",
        "When": "当",
        "When above": "高于时",
        "When below": "低于时",
        "When clicked": "点按时",
        "When closed": "关闭时",
        "When equal": "等于时",
        "When finished": "完成时",
        "When held down": "按住时",
        "When it can't connect": "无法连接时",
        "When it doesn't match": "不符合时",
        "When it matches": "符合时",
        "When it redraws": "重绘时",
        "When it updates": "更新时",
        "When listed": "列出时",
        "When loaded": "载入时",
        "When new data arrives": "有新数据时",
        "When pressed": "按下时",
        "When released": "松开时",
        "When the download fails": "下载失败时",
        "When the pattern fails": "模式不符时",
        "When the place can't be found": "找不到地点时",
        "When the pointer moves": "指针移动时",
        "When the track changes": "换曲时",
        "When the value changes": "数值变化时",
        "While dragging": "拖动时",
        "Wind in": "风速单位",
        "Window class": "窗口类",
        "Window title": "窗口标题",
        "Working folder": "工作文件夹",
        "Zero frame": "零帧",
    ]

    static let choices: [String: String] = [
        "32 / 64 bit": "32 / 64 位",
        "Accent": "强调色",
        "Acrylic": "亚克力",
        "Active connection": "当前连接",
        "Air pressure": "气压",
        "Album": "专辑",
        "All": "全部",
        "All channels": "全部声道",
        "All cores": "全部核心",
        "All displays: height": "全部显示器：高度",
        "All displays: left": "全部显示器：左边",
        "All displays: top": "全部显示器：顶边",
        "All displays: width": "全部显示器：宽度",
        "Alpha": "透明度",
        "App name": "App 名称",
        "App path": "App 路径",
        "Apple Music": "Apple Music",
        "Artist": "艺人",
        "As on this Mac": "和这台 Mac 一样",
        "Authentication": "认证方式",
        "Automatic": "自动",
        "Average": "平均",
        "Back left": "左后",
        "Back right": "右后",
        "Backdrop": "背板",
        "Band frequency": "频段频率",
        "Battery current": "电池电流",
        "Battery cycle count": "电池循环计数",
        "Battery health": "电池健康度",
        "Battery temperature": "电池温度",
        "Battery voltage": "电池电压",
        "Beaufort": "蒲福风级",
        "Blue": "蓝",
        "Blur": "模糊",
        "Both": "两者",
        "Bus speed": "总线速度",
        "Busiest app's name": "最忙的 App 的名称",
        "Busiest app's value": "最忙的 App 的数值",
        "Busy": "繁杂",
        "CPU clock": "CPU 频率",
        "CPU clock (fastest cluster)": "CPU 频率（最快的簇）",
        "CPU core 1 clock": "CPU 核心 1 频率",
        "CPU core 1 temperature": "CPU 核心 1 温度",
        "CPU efficiency cores clock": "CPU 能效核心频率",
        "CPU efficiency cores temperature": "CPU 能效核心温度",
        "CPU performance cores clock": "CPU 性能核心频率",
        "CPU performance cores temperature": "CPU 性能核心温度",
        "CPU power": "CPU 功率",
        "CPU temperature": "CPU 温度",
        "CPU temperature (hottest sensor)": "CPU 温度（最热的传感器）",
        "CPU usage": "CPU 占用率",
        "CPU voltage": "CPU 电压",
        "Center": "居中",
        "Center · Bottom": "居中 · 底部",
        "Center · Middle": "居中 · 中间",
        "Center · Top": "居中 · 顶部",
        "Chance of rain": "降水概率",
        "Chance of thunder": "雷暴概率",
        "Charge (%)": "电量（%）",
        "Chinese (GBK)": "简体中文（GBK）",
        "Chip or chipset temperature": "芯片或芯片组温度",
        "Cloud cover": "云量",
        "Computer name": "电脑名称",
        "Condition": "天气状况",
        "Core load": "核心负载",
        "Core multiplier": "核心倍频",
        "Core speed": "核心频率",
        "Core temperature": "核心温度",
        "Core voltage": "核心电压",
        "Country": "国家或地区",
        "Country code": "国家或地区代码",
        "Cover": "封面",
        "Credit (Based on data from MET Norway)": "署名（Based on data from MET Norway）",
        "Crosshair": "十字线",
        "Cyrillic": "西里尔文",
        "DNS server": "DNS 服务器",
        "Date": "日期",
        "Dawn (astronomical)": "黎明（天文）",
        "Dawn (civil)": "黎明（民用）",
        "Dawn (nautical)": "黎明（航海）",
        "Day or night": "白天或夜晚",
        "Daylight offset": "夏令时偏移",
        "Daylight saving time now": "现在是夏令时",
        "Daylight time zone name": "夏令时时区名称",
        "Desktop": "桌面",
        "Device ID": "设备 ID",
        "Device list": "设备列表",
        "Device status": "设备状态",
        "Dew point": "露点",
        "Disk activity": "磁盘活动",
        "Disk reads": "磁盘读取",
        "Disk writes": "磁盘写入",
        "Domain": "域",
        "Domain / workgroup": "域 / 工作组",
        "Duration": "时长",
        "Dusk (astronomical)": "黄昏（天文）",
        "Dusk (civil)": "黄昏（民用）",
        "Dusk (nautical)": "黄昏（航海）",
        "Encryption": "加密方式",
        "Evening golden hour starts": "傍晚黄金时刻开始",
        "Every 2nd update": "每 2 次更新",
        "Every 5th update": "每 5 次更新",
        "Every update": "每次更新",
        "Fan": "风扇",
        "Fan 1 maximum speed": "风扇 1 最高转速",
        "Fan 1 minimum speed": "风扇 1 最低转速",
        "Fan 1 speed": "风扇 1 转速",
        "Fan 1 target speed": "风扇 1 目标转速",
        "Fan speed (% of its maximum)": "风扇转速（最高转速的 %）",
        "Fan speed (RPM)": "风扇转速（RPM）",
        "Feels like": "体感温度",
        "File": "文件",
        "Files": "文件",
        "Fill": "填充",
        "Filled": "填充",
        "Fit Inside": "适应内部",
        "Fog": "雾",
        "Folders": "文件夹",
        "Forecast made at": "预报发布于",
        "GDI objects": "GDI 对象",
        "GPU Adapter Memory": "GPU 显卡内存",
        "GPU Engine": "GPU 引擎",
        "GPU Process Memory": "GPU 进程内存",
        "GPU clock": "GPU 频率",
        "GPU fan": "GPU 风扇",
        "GPU memory clock": "GPU 显存频率",
        "GPU memory in use": "GPU 显存用量",
        "GPU memory used (MB)": "GPU 显存用量（MB）",
        "GPU power": "GPU 功率",
        "GPU renderer usage": "GPU 渲染器占用率",
        "GPU temperature": "GPU 温度",
        "GPU tiler usage": "GPU 分块器占用率",
        "GPU usage": "GPU 占用率",
        "Gateway": "网关",
        "Gateway (IPv4)": "网关（IPv4）",
        "Gateway (IPv6)": "网关（IPv6）",
        "Genre": "类型",
        "Graphics": "图形",
        "Green": "绿",
        "Help": "帮助",
        "High": "高",
        "Highlight": "高亮",
        "Horizontal": "水平",
        "Host name": "主机名",
        "Hottest core": "最热的核心",
        "How far the day has gone": "今天过了多少",
        "Humidity": "湿度",
        "Hyperlink": "超链接",
        "IP address": "IP 地址",
        "Icon": "图标",
        "Image file": "图片文件",
        "Internet (IPv4)": "互联网（IPv4）",
        "Internet (IPv6)": "互联网（IPv6）",
        "Internet connected": "已连接互联网",
        "Items": "项目",
        "Japanese (Shift-JIS)": "日文（Shift-JIS）",
        "Last sleep": "上次睡眠",
        "Last wake": "上次唤醒",
        "Latitude": "纬度",
        "Left": "左",
        "Left · Bottom": "左 · 底部",
        "Left · Middle": "左 · 中间",
        "Left · Top": "左 · 顶部",
        "Length of the day": "昼长",
        "License link": "许可链接",
        "Link speed in": "接收链接速度",
        "Link speed out": "发送链接速度",
        "Local network (IPv4)": "本地网络（IPv4）",
        "Local network (IPv6)": "本地网络（IPv6）",
        "Local network connected": "已连接本地网络",
        "Log details": "记录细节",
        "Login time": "登录时间",
        "Longitude": "经度",
        "Loudness level": "响度",
        "Low": "低",
        "Luminance": "亮度",
        "Lyrics": "歌词",
        "MAC address": "MAC 地址",
        "Maximum temperature": "最高温度",
        "Memory": "内存",
        "Memory page size": "内存页大小",
        "Memory used (MB)": "内存用量（MB）",
        "Menu": "菜单",
        "Mica": "云母",
        "Mica Acrylic": "云母亚克力",
        "Mica Alt": "云母（替代）",
        "Microphone": "麦克风",
        "Middle": "中间",
        "Midnight sun or polar night": "极昼或极夜",
        "Moon icon (SF Symbol)": "月相图标（SF 符号）",
        "Moon lit (%)": "月亮被照亮的部分（%）",
        "Moon phase": "月相",
        "Moon phase name": "月相名称",
        "Morning golden hour ends": "早晨黄金时刻结束",
        "Move": "移动",
        "Multiplier": "倍频",
        "Name": "名称",
        "Named only": "只有有名字的",
        "Network Adapter": "网络适配器",
        "Network Interface": "网络接口",
        "Network adapter GUID": "网络适配器 GUID",
        "Network adapter alias": "网络适配器别名",
        "Network adapter connected": "网络适配器已连接",
        "Network adapter name": "网络适配器名称",
        "Network adapter status": "网络适配器状态",
        "Network adapter type": "网络适配器类型",
        "Network name": "网络名称",
        "Networks nearby": "附近的网络",
        "No": "否",
        "No proxy": "不用代理",
        "None": "无",
        "Not allowed": "不允许",
        "Number": "数字",
        "Number of displays": "显示器数量",
        "Numeric only": "只有数字",
        "OS name": "系统名称",
        "Off": "关",
        "One frequency slice": "一个频率切片",
        "One sound band": "一个声音频段",
        "Only once": "只一次",
        "Open files": "打开的文件",
        "Outline": "描边",
        "Output device name": "输出设备名称",
        "Paging File": "页面文件",
        "Peak level": "峰值电平",
        "Pen": "笔",
        "Place": "地点",
        "Place, region and country": "地点、地区和国家",
        "Player": "播放器",
        "Plugged in": "已接通电源",
        "Pointing hand": "手形指针",
        "Position": "位置",
        "Power": "功率",
        "Power: CPU": "功率：CPU",
        "Power: GPU": "功率：GPU",
        "Power: Neural Engine": "功率：神经网络引擎",
        "Power: from the adapter": "功率：来自电源适配器",
        "Power: memory": "功率：内存",
        "Power: whole Mac": "功率：整台 Mac",
        "Pressure unit": "气压单位",
        "Process": "进程",
        "Processor": "处理器",
        "Processor Information": "处理器信息",
        "Processor name": "处理器名称",
        "Processor speed": "处理器速度",
        "Processor speed (Hz)": "处理器速度（Hz）",
        "Processor speed (MHz)": "处理器速度（MHz）",
        "Progress": "进度",
        "Rain amount": "降水量",
        "Rain unit": "降水单位",
        "Rating": "评分",
        "Receive rate": "接收速率",
        "Red": "红",
        "Remaining": "剩余",
        "Repeat": "重复",
        "Resize diagonal ↗": "沿对角调整大小 ↗",
        "Resize diagonal ↘": "沿对角调整大小 ↘",
        "Resize left/right": "左右调整大小",
        "Resize up/down": "上下调整大小",
        "Right": "右",
        "Right · Bottom": "右 · 底部",
        "Right · Middle": "右 · 中间",
        "Right · Top": "右 · 顶部",
        "Round": "圆形",
        "Round (Ws)": "圆形（Ws）",
        "Round, small": "圆形，小",
        "SSD temperature": "SSD 温度",
        "Save the page": "存储网页",
        "Scales with the layer": "随图层缩放",
        "Screen height": "屏幕高度",
        "Screen size": "屏幕大小",
        "Screen width": "屏幕宽度",
        "Screenshot": "截屏",
        "Seconds since last input": "上次输入后的秒数",
        "Shared memory": "共享内存",
        "Shared video memory": "共享显存",
        "Short credit (Data: MET Norway)": "简短署名（Data: MET Norway）",
        "Shuffle": "随机播放",
        "Side left": "左侧",
        "Side right": "右侧",
        "Signal quality": "信号质量",
        "Size": "大小",
        "Slice frequency": "切片频率",
        "Solar noon": "正午",
        "Sound format": "声音格式",
        "Source link": "来源链接",
        "Spotify": "Spotify",
        "Square": "方形",
        "Standard offset": "标准时偏移",
        "State": "状态",
        "Status": "状态",
        "Status flags": "状态标志",
        "Status icon (SF Symbol)": "状态图标（SF 符号）",
        "Stays the same": "保持不变",
        "Stretch": "拉伸",
        "Sub-keys": "子键",
        "Subnet mask": "子网掩码",
        "Subwoofer": "低音炮",
        "Sun direction (degrees)": "太阳方位（度）",
        "Sun height (degrees)": "太阳高度（度）",
        "Sunrise": "日出",
        "Sunset": "日落",
        "System": "系统",
        "System settings": "系统设置",
        "Temperature": "温度",
        "Temperature color": "温度颜色",
        "Temperature curve (Shape path)": "温度曲线（形状路径）",
        "Temperature unit": "温度单位",
        "Text (I-beam)": "文字（I 形）",
        "The high": "最高",
        "The low": "最低",
        "The screen's corner": "屏幕的角",
        "The widget's corner": "小组件的角",
        "Thermal Zone Information": "散热区信息",
        "Thermal design power": "热设计功耗",
        "This Mac": "这台 Mac",
        "Time left": "剩余时间",
        "Time of the hour or day": "整点或一天中的时刻",
        "Time zone": "时区",
        "Time zone name": "时区名称",
        "Title": "标题",
        "Total": "总量",
        "Translucent backdrop": "半透明背板",
        "Transmit rate": "发送速率",
        "Type": "类型",
        "USER objects": "USER 对象",
        "UTC offset (minutes)": "UTC 偏移（分钟）",
        "UV index": "紫外线指数",
        "Up arrow": "向上箭头",
        "Updated at": "更新于",
        "User name": "用户名",
        "Value": "数值",
        "Value names": "值的名称",
        "Vertical": "垂直",
        "Video memory": "显存",
        "Voltage": "电压",
        "Volume": "音量",
        "Wait": "等待",
        "Wallpaper": "墙纸",
        "Weather code (MET Norway)": "天气代码（MET Norway）",
        "Weather icon (SF Symbol)": "天气图标（SF 符号）",
        "Western (Latin-1)": "西欧（Latin-1）",
        "What Your Mac Plays": "Mac 播放的声音",
        "Where the place comes from": "地点从哪里来",
        "Wi-Fi standard": "无线局域网标准",
        "Wind direction (N, NE…)": "风向（北、东北…）",
        "Wind direction (degrees)": "风向（度）",
        "Wind force (Beaufort)": "风力（蒲福风级）",
        "Wind gusts": "阵风",
        "Wind speed": "风速",
        "Wind unit": "风速单位",
        "Window": "窗口",
        "Windows": "Windows",
        "Windows user ID": "Windows 用户 ID",
        "Work area height": "工作区高度",
        "Work area left": "工作区左边",
        "Work area size": "工作区大小",
        "Work area top": "工作区顶边",
        "Work area width": "工作区宽度",
        "Year": "年份",
        "inches": "英寸",
        "km/h": "公里/时",
        "knots": "海里/时",
        "m/s": "米/秒",
        "macOS version": "macOS 版本",
        "mm": "毫米",
        "mph": "英里/时",
        "°C, km/h, mm": "°C、公里/时、毫米",
        "°F, mph, in": "°F、英里/时、英寸",
    ]
}
