; Stationery · System — sample loads for each core, for screenshots (SystemSource=Demo). Original work, MIT licensed.
; The same sections as CoreLoads-Live.inc. The sample is a Mac with 10 performance and 4 efficiency cores, whose
; performance cores come in two clusters of five.

[Variables]
DemoP1=34
DemoP2=18
DemoP3=11
DemoP4=6
DemoP5=3
DemoP6=27
DemoP7=12
DemoP8=6
DemoP9=3
DemoP10=2
DemoP11=0
DemoP12=0
DemoP13=0
DemoP14=0
DemoP15=0
DemoP16=0
DemoP17=0
DemoP18=0
DemoP19=0
DemoP20=0
DemoP21=0
DemoP22=0
DemoP23=0
DemoP24=0
DemoP25=0
DemoP26=0
DemoP27=0
DemoP28=0
DemoP29=0
DemoP30=0
DemoP31=0
DemoP32=0
DemoE1=46
DemoE2=42
DemoE3=40
DemoE4=31
DemoE5=0
DemoE6=0
DemoE7=0
DemoE8=0

[MeasureP1]
Measure=Calc
Formula=#DemoP1#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP2]
Measure=Calc
Formula=#DemoP2#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP3]
Measure=Calc
Formula=#DemoP3#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP4]
Measure=Calc
Formula=#DemoP4#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP5]
Measure=Calc
Formula=#DemoP5#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP6]
Measure=Calc
Formula=#DemoP6#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP7]
Measure=Calc
Formula=#DemoP7#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP8]
Measure=Calc
Formula=#DemoP8#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP9]
Measure=Calc
Formula=#DemoP9#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP10]
Measure=Calc
Formula=#DemoP10#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP11]
Measure=Calc
Formula=#DemoP11#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP12]
Measure=Calc
Formula=#DemoP12#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP13]
Measure=Calc
Formula=#DemoP13#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP14]
Measure=Calc
Formula=#DemoP14#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP15]
Measure=Calc
Formula=#DemoP15#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP16]
Measure=Calc
Formula=#DemoP16#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP17]
Measure=Calc
Formula=#DemoP17#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP18]
Measure=Calc
Formula=#DemoP18#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP19]
Measure=Calc
Formula=#DemoP19#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP20]
Measure=Calc
Formula=#DemoP20#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP21]
Measure=Calc
Formula=#DemoP21#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP22]
Measure=Calc
Formula=#DemoP22#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP23]
Measure=Calc
Formula=#DemoP23#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP24]
Measure=Calc
Formula=#DemoP24#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP25]
Measure=Calc
Formula=#DemoP25#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP26]
Measure=Calc
Formula=#DemoP26#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP27]
Measure=Calc
Formula=#DemoP27#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP28]
Measure=Calc
Formula=#DemoP28#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP29]
Measure=Calc
Formula=#DemoP29#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP30]
Measure=Calc
Formula=#DemoP30#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP31]
Measure=Calc
Formula=#DemoP31#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureP32]
Measure=Calc
Formula=#DemoP32#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureE1]
Measure=Calc
Formula=#DemoE1#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureE2]
Measure=Calc
Formula=#DemoE2#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureE3]
Measure=Calc
Formula=#DemoE3#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureE4]
Measure=Calc
Formula=#DemoE4#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureE5]
Measure=Calc
Formula=#DemoE5#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureE6]
Measure=Calc
Formula=#DemoE6#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureE7]
Measure=Calc
Formula=#DemoE7#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores

[MeasureE8]
Measure=Calc
Formula=#DemoE8#
MinValue=0
MaxValue=100
Disabled=(1 - #CoresView#)
Group=Cores
