; Stationery · Countdown — its words in Simplified Chinese. Original work, MIT licensed.
; The same keys as Strings-English.inc.

[Variables]
CountdownNewYear=元旦
CountdownToday=今天
CountdownDay=" 天"
CountdownDays=" 天"
CountdownTomorrowDateRe=明天，\1
CountdownSinceRe=自 \1 起
CountdownBadDate=读不懂日期
CountdownOfYear=一年已过 %1%
CountdownOfWait=等待已过 %1%
CountdownMenuEdit=编辑事件…
CountdownMenuRepeat1=重复：每年
CountdownMenuRepeat0=重复：从不
CountdownTipToday=今天就是\1（\2）。
CountdownTipTomorrow=明天就是\1（\2）。
CountdownTipLaterYear=距离\1（\2）还有 \3 天。一年已过 \4%。
CountdownTipLaterWait=距离\1（\2）还有 \3 天。等待已过 \4%。
CountdownTipYesterday=\1是昨天（\2）。
CountdownTipAgo=\1已过去 \3 天（\2）。
CountdownTipBad=读不懂\1的日期。右键 › 编辑事件…，按 2027-01-01 的格式输入。
